import {createHmac,timingSafeEqual,randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {isIP} from 'node:net';
export function sign(payload:Record<string,unknown>,secret:string){if(secret.length<32)throw new Error('Missing signing key');const body=Buffer.from(JSON.stringify(payload)).toString('base64url');return `${body}.${createHmac('sha256',secret).update(body).digest('base64url')}`;}
export function verify<T>(token:string|undefined,secret:string,now=Date.now()):T|null{try{if(!token||token.length>4096||secret.length<32)return null;const parts=token.split('.');if(parts.length!==2)return null;const [body,signature]=parts;const actual=Buffer.from(signature,'base64url');const expected=createHmac('sha256',secret).update(body).digest();if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return null;const p=JSON.parse(Buffer.from(body,'base64url').toString());if(typeof p.exp!=='number'||p.exp<=now)return null;return p as T;}catch{return null;}}
function encryptionKey(hex:string){if(!/^[a-f0-9]{64}$/i.test(hex))throw new Error('IP_ENCRYPTION_KEY must be 32 bytes of hex');return Buffer.from(hex,'hex');}
export function encryptIP(ip:string,key:string){if(!isIP(ip))throw new Error('Invalid IP');const nonce=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',encryptionKey(key),nonce);cipher.setAAD(Buffer.from('waylan-ip-v1'));const encrypted=Buffer.concat([cipher.update(ip,'utf8'),cipher.final()]);return ['v1',nonce.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.');}
export function decryptIP(value:string,key:string){const [v,n,t,c]=value.split('.');if(v!=='v1'||!n||!t||!c)throw new Error('Invalid encrypted IP');const decipher=createDecipheriv('aes-256-gcm',encryptionKey(key),Buffer.from(n,'base64url'));decipher.setAAD(Buffer.from('waylan-ip-v1'));decipher.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([decipher.update(Buffer.from(c,'base64url')),decipher.final()]).toString('utf8');}
export function normalizeIP(value:string){const raw=value.trim();if(raw.includes('%')||!isIP(raw))return null;if(raw.startsWith('::ffff:')&&isIP(raw.slice(7))===4)return raw.slice(7);if(isIP(raw)===6){return new URL(`http://[${raw}]`).hostname.slice(1,-1);}return raw;}
export function ipHash(ip:string,key:string){return createHmac('sha256',encryptionKey(key)).update(`visitor:${ip}`).digest('hex');}
export function requestIP(headers:Headers,vercel:boolean,clientAddress:string){return normalizeIP(vercel ? (headers.get('x-vercel-forwarded-for')||'').split(',')[0] : clientAddress);}
export function sameOrigin(request:Request,origin:string){return request.headers.get('origin')===origin && !['cross-site','none'].includes(request.headers.get('sec-fetch-site')||'');}
export function sourceHost(referrer:unknown){if(typeof referrer!=='string'||referrer.length>2048)return '';try{const u=new URL(referrer);return ['http:','https:'].includes(u.protocol)?u.hostname.slice(0,253):'';}catch{return '';}}
export async function smallJSON(request:Request,limit=4096):Promise<Record<string,unknown>>{if(!request.headers.get('content-type')?.startsWith('application/json'))throw new Error('Unsupported body');if(Number(request.headers.get('content-length')||0)>limit)throw new Error('Body too large');const reader=request.body?.getReader();if(!reader)throw new Error('Missing body');const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new Error('Body too large');}chunks.push(value);}const result=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!result||typeof result!=='object'||Array.isArray(result))throw new Error('Invalid body');return result;}
export function safePath(path:unknown,allowed:Set<string>){if(typeof path!=='string'||path.length>180)return null;const normalized=path==='/'?'/':path.replace(/\/$/,'')+'/';return allowed.has(normalized)?normalized:null;}
export const privateHeaders={'Cache-Control':'private, no-store','X-Robots-Tag':'noindex, nofollow','Vary':'Cookie'};
export function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...privateHeaders,'Content-Type':'application/json; charset=utf-8'}});}
