export {};
type Row={viewed_at:string;ip:string;path:string;referrer_host:string;country:string};
type Stats={summary:{views:number;visitors:number;pages:number};daily:{day:string;views:number;visitors:number}[];pages:{path:string;views:number}[];sources:{referrer_host:string;views:number}[];rows:Row[];filters:{days:number;page:number};retention:number};
const form=document.querySelector<HTMLFormElement>('#filters')!;
const dashboardStatus=document.querySelector<HTMLElement>('#dashboard-status')!;
const previous=document.querySelector<HTMLButtonElement>('#previous-page')!,next=document.querySelector<HTMLButtonElement>('#next-page')!;
let page=1;let controller:AbortController|undefined;
const fmt=new Intl.NumberFormat('zh-TW');
const dateFmt=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
function element<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''){const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;}
function setMetric(id:string,value:number|string){document.getElementById(id)!.textContent=typeof value==='number'?fmt.format(value):value;}
function placeholder(message:string){const body=document.getElementById('visit-rows')!;body.replaceChildren();const tr=element('tr'),td=element('td',message);td.colSpan=5;tr.append(td);body.append(tr);}
function renderRanks(id:string,data:{label:string;value:number}[]){const list=document.getElementById(id)!;list.replaceChildren();if(!data.length){list.append(element('li','此期間尚無紀錄。','muted'));return;}for(const item of data){const li=element('li');li.append(element('span',item.label),element('span',fmt.format(item.value)));list.append(li);}}
function renderTrend(data:Stats){const chart=document.getElementById('trend')!;chart.replaceChildren();const max=Math.max(1,...data.daily.map(d=>d.views));const now=new Date();const end=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const start=new Date(`${end}T00:00:00+08:00`);start.setUTCDate(start.getUTCDate()-data.filters.days);for(let i=0;i<=data.filters.days;i++){const d=new Date(start.getTime()+i*86400000);const key=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);const value=data.daily.find(r=>r.day===key)?.views||0;const group=element('div','','trend-day');group.title=`${key}：${value} 次瀏覽`;group.setAttribute('aria-label',group.title);const bar=element('div','','trend-column');bar.style.height=`${Math.max(1,value/max*160)}px`;const label=(data.filters.days<=7||i%5===0||i===data.filters.days)?key.slice(5).replace('-','/'):'';group.append(element('span',value&&data.filters.days<=7?String(value):'','trend-value'),bar,element('span',label,'trend-label'));chart.append(group);}}
function render(data:Stats){setMetric('metric-views',data.summary.views);setMetric('metric-visitors',data.summary.visitors);setMetric('metric-pages',data.summary.pages);renderTrend(data);renderRanks('top-pages',data.pages.map(p=>({label:p.path,value:p.views})));renderRanks('sources',data.sources.map(p=>({label:p.referrer_host||'直接造訪 / 未提供來源',value:p.views})));const body=document.getElementById('visit-rows')!;body.replaceChildren();if(!data.rows.length)placeholder('此範圍內尚無來訪紀錄。');for(const row of data.rows){const tr=element('tr');const ip=element('td');const button=element('button',row.ip,'ip-button');button.type='button';button.addEventListener('click',()=>{(form.elements.namedItem('ip') as HTMLInputElement).value=row.ip;page=1;void load();});ip.append(button);tr.append(element('td',dateFmt.format(new Date(row.viewed_at))),ip,element('td',row.path),element('td',row.referrer_host||'直接造訪'),element('td',row.country||'—'));body.append(tr);}const pages=Math.max(1,Math.ceil(data.summary.views/25));document.getElementById('page-status')!.textContent=`PAGE ${page} / ${pages}`;previous.disabled=page<=1;next.disabled=page>=pages;dashboardStatus.textContent=data.summary.views?`已更新 · 最近 ${data.filters.days} 天 · ${fmt.format(data.summary.views)} 筆紀錄`:'此期間尚無統計資料。造訪公開頁面後，再套用篩選即可更新。';}
async function load(){controller?.abort();const current=new AbortController();controller=current;dashboardStatus.textContent='正在讀取紀錄…';dashboardStatus.dataset.error='false';previous.disabled=true;next.disabled=true;const params=new URLSearchParams();new FormData(form).forEach((value,key)=>params.set(key,String(value)));params.set('page',String(page));try{const response=await fetch(`/api/admin/stats?${params}`,{signal:current.signal,cache:'no-store'});if(response.status===401){location.href='/admin/login/';return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'暫時無法讀取資料。');render(data);}catch(e){if(current.signal.aborted)return;dashboardStatus.dataset.error='true';dashboardStatus.textContent=e instanceof Error?e.message:'無法讀取資料。';['metric-views','metric-visitors','metric-pages'].forEach(id=>setMetric(id,'—'));placeholder('資料讀取失敗，請稍後重新套用篩選。');document.getElementById('trend')!.replaceChildren();renderRanks('top-pages',[]);renderRanks('sources',[]);}}
form.addEventListener('submit',e=>{e.preventDefault();page=1;void load();});form.addEventListener('reset',()=>{page=1;setTimeout(()=>void load(),0);});previous.addEventListener('click',()=>{if(page>1){page--;void load();}});next.addEventListener('click',()=>{page++;void load();});void load();
